In [2]:
# DAV Experiment 1 - NumPy and Pandas

import numpy as np
import pandas as pd

print("========== NUMPY ==========")


a = np.array([10, 20, 30, 40, 50])
print("Array:", a)



========== NUMPY ==========
Array: [10 20 30 40 50]


In [3]:
# Array attributes
print("Dimensions:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data type:", a.dtype)



Dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


In [4]:
# Indexing and slicing
print("First element:", a[0])
print("Last element:", a[-1])
print("Slicing:", a[1:4])



First element: 10
Last element: 50
Slicing: [20 30 40]


In [5]:
# Array operations
b = np.array([1, 2, 3, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)



Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]


In [6]:
# Mathematical functions
print("Square root:", np.sqrt(a))
print("Square:", np.square(a))



Square root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Square: [ 100  400  900 1600 2500]


In [7]:
# Statistical functions
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))
print("Standard deviation:", np.std(a))

# Reshape
c = np.arange(1, 10)
print("Original:", c)
print("Reshaped:\n", c.reshape(3, 3))




Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10
Standard deviation: 14.142135623730951
Original: [1 2 3 4 5 6 7 8 9]
Reshaped:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# ---------------- PANDAS ----------------

print("\n========== PANDAS ==========")

# Creating a Series
marks = pd.Series([85, 90, 78, 92, 88])
print("Series:\n", marks)

# Creating a DataFrame
data = {
    "Name": ["Anu", "Bharath", "Chitra", "Deepak", "Esha"],
    "Age": [20, 21, 20, 22, 21],
    "Marks": [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)

print("\nDataFrame:")
print(df)

# DataFrame information
print("\nShape:", df.shape)
print("Columns:", df.columns)

# First and last rows
print("\nFirst 3 rows:")
print(df.head(3))

print("\nLast 2 rows:")
print(df.tail(2))

# Selecting columns
print("\nNames:")
print(df["Name"])

# Selecting rows
print("\nFirst row:")
print(df.iloc[0])

# Filtering
print("\nStudents with marks above 85:")
print(df[df["Marks"] > 85])

# Sorting
print("\nSorted by marks:")
print(df.sort_values("Marks", ascending=False))

# Statistical summary
print("\nStatistics:")
print(df["Marks"].describe())

# Add a new column
df["Result"] = ["Pass", "Pass", "Pass", "Pass", "Pass"]

print("\nUpdated DataFrame:")
print(df)

# Save as CSV
df.to_csv("students.csv", index=False)

print("\nData saved to students.csv")